### ISSUE TITLE
Waarom is minimum marktkapitalisatie belangrijk? 

### ISSUE THREAD

**Issue by CoenraadS** [nicwortel/indexfondsenvergelijken.nl#12]
Hi, omdat de default op 70% is, is `NN Enhanced + NN Enhanced EM` niet zichtbaar omdat de grens op 57% ligt.

Het is niet duidelijk voor mij wat dit allemaal betekent.

**Comment by nicwortel** [comment]
Hoi @CoenraadS,

Bedankt voor je feedback. Allereerst het antwoord op je vraag.

De uitleg van het begrip marktkapitalisatie is een beetje verborgen in de [veelgestelde vragen](https://www.indexfondsenvergelijken.nl/veelgestelde-vragen.html):

> ### Wat is marktkapitalisatie?
> De _marktkapitalisatie_ (ook wel beurswaarde, of in het Engels _market cap_) van een bedrijf is de totale waarde van alle aandelen van dat bedrijf. Het wordt berekend door het aantal uitstaande aandelen te vermenigvuldigen met de actuele koers op de beurs. Als een bedrijf dus 100.000 aandelen uitgegeven heeft die elk € 10 waard zijn, heeft dat bedrijf een marktkapitalisatie van € 1.000.000. Als er gesproken wordt over de marktkapitalisatie van een index dan wordt de som van de marktkapitalisatie van alle opgenomen bedrijven bedoeld. Dit geeft dus een beeld van de grootte van de markt die de index beslaat.
> 
> Op deze website wordt de marktkapitalisatie van portefeuilles getoond als een percentage van de totale investeerbare wereldmarkt. Dit geeft een indicatie van het deel van de totale wereldmarkt waarin wordt belegd door een portefeuille. Deze percentages worden berekend door voor elk fonds de marktkapitalisatie van de gevolgde index te nemen, hier de ESG-uitsluitingen van af te trekken, en de som van deze bedragen te delen door de marktkapitalisatie van de MSCI ACWI IMI index.

Simpel gezegd: hoe groter de marktkapitalisatie van je portefeuille, hoe beter je beleggingen (en dus je risico) gespreid zijn over de gehele wereldmarkt. Dit is de basis van de beleggingsstrategie (wereldwijd gespreid indexbeleggen) waar deze website op gebaseerd is.

De portefeuille met de fondsen van Nationale Nederlanden wijkt hier van af door zo veel bedrijven uit te sluiten (op basis van ESG criteria) dat de combinatie van deze twee fondsen "slechts" in 57% van de wereldwijd beschikbare marktkapitalisatie belegt. De afwijking van de index (MSCI World en MSCI Emerging Markets) is daarmee dusdanig groot dat je meer risico's gaat lopen. Dat is prima als je daar bewust voor kiest, maar als deze portefeuille met de standaard instellingen bovenaan staat zal niet iedereen zich daar bewust van zijn. Dat is de reden waarom ik dit filter heb toegevoegd.

Beantwoordt dit je vraag? Ik besef dat dit vrij complexe materie is (het heeft mij ook een tijd gekost om dit te begrijpen). Als je ideeën hebt hoe ik dit duidelijker kan maken op mijn website, dan hoor ik het graag!

**Comment by CoenraadS** [comment]
Prima uitleg!

Misschien op de website naast de 'Minimum marktkapitalisatie' tekst een [?] icon waar met de muis over kan hoveren.

En dan een kort tekst, deze zin was goed te begrijpen voor mij.

>"slechts" in n% van de wereldwijd beschikbare marktkapitalisatie belegt. De afwijking van de index (MSCI World en MSCI Emerging Markets) is daarmee dusdanig groot dat je meer risico's gaat lopen. "
