### ISSUE TITLE
Meesman calculation missing Fund Service Fees?

### ISSUE THREAD

**Issue by marceldegraaf** [nicwortel/indexfondsenvergelijken.nl#16]
The [Meesman website](https://www.meesman.nl/zo-werkt-het/kosten) lists Transaction Fees of 0,25% which seem to be taken into account in the calculator on indexfondsenvergelijken.nl. However, they also mention Fund Service Fees (Fondskosten) of 0,4% when investing in their Aandelen Wereldwijd Totaal fund, and 0,5% for their other funds.

It looks like these fees are not taken into account for the calculations on indexfondsenvergelijken.nl. Or am I missing something?

**Comment by nicwortel** [comment]
Hi Marcel,

Thanks for opening your first issue here! I separate the fund costs from the broker costs. That can be a bit confusing for Meesman (as Meesman is both the fund manager and the broker) but makes more sense for other funds and ETF's. When looking at the "Tarieven" tab you will only see the broker costs. You can see the 0.4% "lopende kosten" when you click on the "Portefeuille" tab.

![afbeelding](https://user-images.githubusercontent.com/1055691/147661757-e6d5ff64-4c34-4b9b-9476-9244710d58d4.png)

If you're comfortable reading JSON then you can also see the raw data in https://github.com/nicwortel/indexfondsenvergelijken.nl/blob/master/data/funds.json#L70-L82.

Does that answer your question?

**Comment by marceldegraaf** [comment]
Hi, Nic – thanks for your quick reply, and thanks for clearing that up. I did check the JSON file but apparently still missed that 0,4% running costs. Makes sense, so I'll close this issue. Cheers!
