### ISSUE TITLE
Lynx and IB hebben verschillende portfolio's

### ISSUE THREAD

**Issue by BartLH** [nicwortel/indexfondsenvergelijken.nl#17]
Lynx is een reseller van IB. Het zou dus logisch zijn als het portfolioaanbod van beide identiek is, met enkel andere kosten. 
Maar dat is niet zo, voor IB zijn VWRL en IWDA + EIMM er, terwijl voor Lynx AVIAW + EMIM en AVIAW + EMIM + IUSN er zijn.

**Comment by nicwortel** [comment]
Hoi Bart, bedankt voor het melden. Je hebt inderdaad gelijk.
Ik heb nu de tarieven van Interactive Brokers voor beleggingsfondsen ingesteld en de portfolio's met AVIAW bij Interactive Brokers toegevoegd aan de vergelijking.

**Comment by gerbenvl** [comment]
ADIAOL is helaas bij zowel IBKR als Lynx niet verkrijgbaar. Die optie zou ik dus weglaten.

**Comment by nicwortel** [comment]
> ADIAOL is helaas bij zowel IBKR als Lynx niet verkrijgbaar. Die optie zou ik dus weglaten.

Oh, wat stom! Ik heb speciaal een IBKR account aangemaakt om te checken welke fondsen en ETF's beschikbaar zijn, en dit fonds is te vinden in het client portal, maar ik had niet gezien dat deze restricted is voor retail clients... Bedankt voor het opmerken! Ik ga deze weer weghalen (zowel voor IBKR als Lynx).

![afbeelding](https://user-images.githubusercontent.com/1055691/148985218-221f6950-5dee-46e8-b09c-fd0093cf1628.png)

Ik heb overigens geen Lynx account maar ga er vanuit dat daar inderdaad dezelfde restrictie geldt.

**Comment by BartLH** [comment]
Top, snel opgelost! Inderdaad jammer dat IB niet de juiste documentatie voor ADIAO wil toevoegen.
Ik zat ook nog even naar de andere portfolio's te kijken en zag dat er soms IEMM, soms EMIM wordt gebruikt. Is dat bewust? Anders kan dat misschien ook worden geconsolideerd naar EMIM. Ze hebben vrijwel identieke kosten.

**Comment by gerbenvl** [comment]
Het gaat IB dacht ik niet om de documentatie. Ze hebben er moeite mee dat het geen UCITS fonds is. Vandaar dat je bijna geen enkel NL fonds op IB verhandelbaar ziet. Blijkbaar kost het veel moeite IB te overtuigen dat UCITS niet van toepassing is voor Nederlanders op deze fondsen.

EMIM heeft small caps, IEMM niet. Denk dat daarom er soms in combinaties gewisseld wordt?

**Comment by BartLH** [comment]
>EMIM heeft small caps, IEMM niet. Denk dat daarom er soms in combinaties gewisseld wordt?

Dat klopt, maar waarom zou je *geen* EM small caps willen?

Vroeger zat EMIM niet in de kernselectie van DeGiro en IEMM wel, maar had IEMM een flink hogere TER. Tegenwoordig is dat veranderd en hebben ze dezelfde TER en zitten ze allebei in de kernselectie.

Ik vermoed dat dat toentertijd tot wat verschillende optimale combinaties heeft geleid, afhankelijk van de broker. Tegenwoordig zie ik echter geen enkele reden om IEMM nog te gebruiken.
