### ISSUE TITLE
ABN Amro voegt 200 ETF's toe aan Zelf Beleggen Basis + transactiekosten zullen gratis zijn

### ISSUE THREAD

**Issue by PMK** [nicwortel/indexfondsenvergelijken.nl#22]
Vanaf maart dit jaar zal ABN Amro 200 ETF's toevoegen aan Zelf Beleggen Basis, en de transactiekosten op ETF's zullen gratis zijn.

Dat maakt VWRD (Vanguard FTSE All-World UCITS ETF IE00B3RBWM25) interessant om te vergelijken.

Zie https://www.abnamro.nl/nl/media/zelf-beleggen-basis-assortiment-januari-2022_tcm16-143056.pdf

**Comment by gilgamezh** [comment]
I saw the message in my account "Good news: you no longer need to pay transaction costs for ETFs within the Self Directed Investing Basic selection. You can choose from over 200 ETFs, many of which are qualified as sustainable."  

It would be really nice to see how it changes the comparisons

**Comment by gilgamezh** [comment]
Also asked here in case we can get more input :-) https://www.reddit.com/r/DutchFIRE/comments/u0d761/etfs_without_transaction_fee_in_abn_any_advantage/

**Comment by nicwortel** [comment]
Thank you @PMK for reporting this, and @gilgamezh for the reminder!

I have just updated the ETF transaction costs for ABN. It doesn't change the comparison with other brokers a lot, as the service fee remains unchanged.

**Comment by gilgamezh** [comment]
thanks!
