### ISSUE TITLE
Hernoem "Verwacht resultaat" naar iets minder ambigu

### ISSUE THREAD

**Issue by morepurplemorebetter** [nicwortel/indexfondsenvergelijken.nl#27]
Ten eerste, heel erg bedankt voor het maken van deze tool!

Voor beginnelingen in ETF-beleggen zoals ik, is het niet meteen duidelijk dat het "Verwacht resultaat" niet het totaal inclusief de inleg is, maar het totaal aan toename.

Ik stel voor om dit dan ook anders te verwoorden. Zou je misschien "Verwachte toename", "Verwachte netto toename", of "Verwachte winst" willen overwegen in plaats van "Verwacht resultaat"?
Of het totaal aan inleg bij verwacht resultaat optellen al dan niet een derde kolom toevoegen waarbij de inleg opgeteld is bij de verwachte toename?

Ik heb hier ook een [reddit post op /r/DutchFIRE voor opgestart](https://redd.it/znbf89), want ik acht het waarschijnlijk dat anderen met een betere naam komen dan ik.

**Comment by nicwortel** [comment]
Hoi @morepurplemorebetter, bedankt voor het aanmaken van dit issue. Ik zie dat de thread op Reddit gesloten is als off-topic, maar dat er inderdaad meer mensen zijn die dit verwarrend vinden.

Ik denk zelf dat "Verwacht rendement" een betere verwoording is. Dat moet hopelijk duidelijk zijn voor zowel mensen die zich al langer bezighouden met beleggen, als voor mensen die er nog niet zo veel kennis van hebben. Wat denk jij?

Met betrekking tot het tonen van het totale vermogen (inleg + verwacht rendement): dit heb ik eerder wel in het overzicht opgenomen. Helaas stonden er op een gegeven moment zoveel bedragen op het scherm dat het alleen maar minder overzichtelijk werd.
Het risico (en dat is er nog steeds met het huidige overzicht) is bovendien dat men gaat focussen op het verwachte rendement / eindvermogen, terwijl je die niet echt met elkaar kunt vergelijken omdat verschillende indexen in de praktijk een verschillend rendement zullen behalen. Daarom heb ik geprobeerd om de aandacht meer op de kosten en op de marktkapitalisatie te richten, en als onderdeel daarvan laat ik het geschatte vermogen niet meer zien.

**Comment by morepurplemorebetter** [comment]
Hallo Nic Wortel,

Bedankt voor de uitgebreide reactie. "Verwacht rendement" klinkt inderdaad als een beter alternatief. Ik denk dat een kopje in de veelgestelde vragen ook niet zou misstaan. Dat kan zo simpel zijn als:

> ### Wat is Verwachte rendement?
> Het verwachte rendement is het geschatte resultaat van de beleggingen minus de geschatte kosten. Hierin is de eigen inleg niet meegenomen. Het totaal aan eigen inleg is te zien in de instellingen.

**Comment by nicwortel** [comment]
Bedankt voor je suggestie. Ik heb de term in het overzicht aangepast en een kopje aan de veelgestelde vragen toegevoegd.
