### ISSUE TITLE
Kosten Saxo bij periodiek beleggen.

### ISSUE THREAD

**Issue by teunlielu** [nicwortel/indexfondsenvergelijken.nl#28]
Als via Saxo periodiek belegd vervallen de transactiekosten. Kijk maar in de link: https://www.home.saxo/nl-nl/accounts/standard-plans
Misschien met * of zo vermelden.

**Comment by nicwortel** [comment]
Ik sluit dit issue alvast, zie #49 voor de discussie rondom de kosten van Saxo AutoInvest.
