### ISSUE TITLE
Costs for ABN are out of date

### ISSUE THREAD

**Issue by miguelci** [nicwortel/indexfondsenvergelijken.nl#39]
For already some time, the costs are different:
<img width="595" alt="image" src="https://github.com/nicwortel/indexfondsenvergelijken.nl/assets/2892689/51782e11-f284-484d-9225-9a089a086322">

https://www.abnamro.nl/en/personal/investments/types-of-investing/self-directed-investing-basic/index.html

see: More information and conditions -> costs

**Comment by ArdaXi** [comment]
ABN Amro lists their service costs as annual, but charges them each quarter. So the calculation also takes them into account quarterly. The information is correct.

**Comment by miguelci** [comment]
but aren't these the numbers being used in the application? they seem wrong from what i posted above no?

```
{
        "name": "ABN Amro",
        "logo": "abn.png",
        "product": "Zelf Beleggen Basis",
        "serviceFee": {
            "tiers": [
                {"upperLimit": 100000, "percentage": 0.05},
                {"upperLimit": 400000, "percentage": 0.03},
                {"upperLimit": null, "percentage": 0.015}
            ]
        },
```

**Comment by ArdaXi** [comment]
You missed the very next line.

`"serviceFeeCalculation": "endOfQuarter",`

**Comment by miguelci** [comment]
oh okok, got it. was focusing on the actual percentage number and didn't reach that part.
thanks!

**Comment by nicwortel** [comment]
No worries @miguelci, it's actually a common mistake and I have to figure out a way to make this more clear on the website to prevent the confusion. Either way, thank you for contributing to the accuracy of the website!

And @ArdaXi thank you for helping to sort it out, I have been busy with other things lately and must have missed this issue :sweat_smile:
