### ISSUE TITLE
Kosten easyBroker kloppen niet

### ISSUE THREAD

**Issue by sfdjo435** [nicwortel/indexfondsenvergelijken.nl#41]
In het kostenplaatje staat dat ze 50% minder transactiekosten zouden hebben de IBKR.

Alleen easyBroker is een reseller van IBKR en rekenen extra fees.

![image](https://github.com/nicwortel/indexfondsenvergelijken.nl/assets/9902911/6dc44543-42a4-49c8-9988-d7e03a366e65)

**Comment by nicwortel** [comment]
Wat zouden de juiste tarieven moeten zijn volgens jou?

In het door jou gedeelde screenshot zie je aan de linkerkant de tarieven waarmee gerekend wordt. Zoals je ziet zijn de tarieven van Easybroker iets hoger dan die van Interactive Brokers, met als uitzondering dat Easybroker [geen minimum transactiekosten rekent voor beleggingsfondsen](https://www.easybroker.nl/tarieven/beleggingsfondsen).

![afbeelding](https://github.com/nicwortel/indexfondsenvergelijken.nl/assets/1055691/103d35cc-1db9-4fdb-b177-fa21e331e34f)

Interactive Brokers rekent wel een minimum transactiekosten van € 4 per transactie, dus dat tikt nogal aan als je niet duizenden euro's per maand inlegt.

Misschien zie ik iets over het hoofd, maar zover ik nu kan zien klopt het gewoon. Zo niet dan hoor ik graag wat er precies niet klopt.
