### ISSUE TITLE
Twee keer CARIW+CARIEM

### ISSUE THREAD

**Issue by thoutenbos** [nicwortel/indexfondsenvergelijken.nl#43]
Sinds de laatste update staat deze combinatie er twee keer in met verschillende verhoudingen…

CARIW (89) met CARIEM (11)
Voor Saxo Bank

CARIW (84) met CARIEM (16)
Voor Saxo, IB, Lynx en Easy

**Comment by thoutenbos** [comment]
Thanks Jake!

Is CARIEM only available at Saxo?

**Comment by nicwortel** [comment]
@thoutenbos bedankt voor het melden! Het was mij niet opgevallen. Ik heb de fix van @jakedane zojuist doorgevoerd.
