### ISSUE TITLE
Saxo maandelijks inleg

### ISSUE THREAD

**Issue by teunlielu** [nicwortel/indexfondsenvergelijken.nl#49]
Als je via Saxo maandelijks automatisch inleg vervallen de transactie kosten. Zie link hieronder:
https://www.help.saxo/hc/nl/articles/7392487859357-Wat-is-AutoInvest.
Om minst waard om eerlijke vergelijking te maken. Zeker omdat je vanuit gaat van een mogelijke inleg.
Misschien met disclaimer.

**Comment by nicwortel** [comment]
Sorry, ik zie dat je meer dan een jaar geleden dit ook al hebt gemeld in #28, maar dat ik daar toen niet op heb gereageerd.

Ik zie ook dat Saxo in mei haar tarieven en "rekeningniveaus" gaat aanpassen, dus ik zal gelijk eens alle tarieven van Saxo updaten.

**Comment by teunlielu** [comment]
Ik kan dat wel na lopen.
Ik kan wel even testen of volledige lijst voorkomt in periode belegen valt.
https://github.com/nicwortel/indexfondsenvergelijken.nl/blob/master/data/funds.json
Moet dat per fonds een screenshot of ja of nee voldoende?

**Comment by teunlielu** [comment]
Geen probleem van je geen reactie op oude ticket

**Comment by nicwortel** [comment]
> Moet dat per fonds een screenshot of ja of nee voldoende?

Je kan inderdaad ook wel hier gewoon een lijstje plaatsen met per fonds/ETF of die wel of niet door AutoInvest ondersteund wordt.
Dan gebruik ik dit issue als 'bron' voor die informatie aangezien Saxo dit zelf niet publiceert.

**Comment by teunlielu** [comment]
Bij dezen lijst van Saxo bank.
**On saxo** is dat kan vinden op Saxo. 
 **AutoInvest** of ik mogelijkerwijs kan toevoegen aan AutoInvest.  Misschien kunnen ze die handmatig nog toevoegen maar dan staat zeker niet in AutoInvest
[autoInvest.csv](https://github.com/nicwortel/indexfondsenvergelijken.nl/files/14950800/autoInvest.csv)
Mogelijkerwijs wordt deze lijst aangepast aan populariteit of hun visie

**Comment by teunlielu** [comment]
Alleen etf en fondsen gecheckt van volgende url
https://github.com/nicwortel/indexfondsenvergelijken.nl/blob/master/data/funds.json

**Comment by nicwortel** [comment]
Bedankt!

Zo te zien ondersteunen alle fondsen die op deze site aan Saxo gekoppeld zijn AutoInvest, maar niet alle ETF's (VWRL/VWCE wel, maar de iShares ETF's niet). En op dit moment kan de vergelijker alleen onderscheid maken tussen de tarieven van fondsen en ETF's, en niet tussen ETF's onderling die wel of niet in een bepaalde selectie zitten.

Op dit moment kan ik dus twee dingen doen:

1. Hernoemen naar Zelf Beleggen AutoInvest, alle transactiekosten op 0 zetten, en Saxo (voorlopig) niet meer tonen bij portefeuilles die niet met AutoInvest werken
2. De transactiekosten voor fondsen op 0 zetten en de transactiekosten voor ETF's instellen op de tarieven van Bronze. Hierdoor kunnen alle portefeuilles blijven staan maar worden er transactiekosten meegerekend bij VWRL en VWCE terwijl die in de werkelijkheid niet berekend worden

Ik neig zelf naar optie 1 omdat er dan geen foutieve informatie getoond wordt en dit voor minder verwarring zal zorgen. Wat denk jij?

**Comment by teunlielu** [comment]
Je kan ook twee brokers aanmaken.
**Saxo AutoInvest** alles wat deze ondersteund
**Saxo** de rest. Met transactie kosten

**Comment by nicwortel** [comment]
> Je kan ook twee brokers aanmaken. **Saxo AutoInvest** alles wat deze ondersteund **Saxo** de rest. Met transactie kosten

Ah, dat is inderdaad een goed idee. Heb ik zojuist doorgevoerd. :+1:

**Comment by teunlielu** [comment]
Ik zie dat ik na controle dat ik fout heb gemaakt.
Saxo AutoInvest Werkt meestal alleen voor de NL beurs. Maar komt niet altijd op NL Beurs terecht standaard.
Daardoor leek aantal dat niet Saxo AutoInvest ondersteunde terwijl ze wel konden.
Bij dezen de geüpdatet lijst met extra kolom met de aangepaste versie.
[autoInvest.csv](https://github.com/nicwortel/indexfondsenvergelijken.nl/files/15067567/autoInvest.csv)
