### ISSUE TITLE
Update Saxo bank maandelijks inleg.

### ISSUE THREAD

**Issue by teunlielu** [nicwortel/indexfondsenvergelijken.nl#51]
@nicwortel 
Ik zie dat ik na controle dat ik fout heb gemaakt.
Saxo AutoInvest werkt meestal alleen voor de NL beurs. Maar komt niet altijd op NL Beurs terecht standaard.
Daardoor leek aantal dat niet Saxo AutoInvest ondersteunde terwijl ze wel konden.
Bij dezen de geüpdatet lijst met extra kolom met de aangepaste versie.
[autoInvest.csv](https://github.com/nicwortel/indexfondsenvergelijken.nl/files/15067567/autoInvest.csv)

_Originally posted by @teunlielu in https://github.com/nicwortel/indexfondsenvergelijken.nl/issues/49#issuecomment-2070700202_

**Comment by nicwortel** [comment]
Ik moest even tijd vinden om hier weer in te duiken.

Hoe moet ik dit bestand interpreteren? Ik zie drie rijen waar in de kolom `AutoInvest` een `X` staat maar in de kolom `AutoInvest (22-4-2024)` een `V`:

- IE00B4L5Y983 (IWDA)
- IE00BKM4GZ66 (EMIM)

IE00BKM4GZ66 staat trouwens dubbel in het bestand.

Betekent dit dat deze twee ETF's **wel** beschikbaar zijn voor AutoInvest en dus goedkoper kunnen zijn bij Saxo Bank?

**Comment by teunlielu** [comment]
Tweede kolom is zoals ik het eerste instantie op gaf.  Correctie is derde kolom. Zodat je kan zien wat verschil is en deze kan updaten.  Dus twee die jij noemt kunnen via AutoInvest
Reden van de fout is:
AutoInvest werkt alleen op NL beurs voor specifieke etf en Fondsen. Als je zoekt kom je niet altijd op nl beurs uit. Waardoor je niet direct ziet of beschikbaar is voor  AutoInvest. Je moet eerst naar nl zetten. Daardoor heb ik die fout gemaakt.

**Comment by nicwortel** [comment]
> IE00BKM4GZ66 staat trouwens dubbel in het bestand.

Ik zie overigens dat IE00BF4RFH31 (IUSN / iShares MSCI World Small Cap UCITS ETF) als enige ontbreekt in jouw bestand, kun je voor mij nog nakijken of deze wel/niet beschikbaar is via AutoInvest?

**Comment by teunlielu** [comment]
IE00BF4RFH31 is verkrijgbaar via Saxo maar niet via AutoInvest te kopen.
